name: flutter_talentaku
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  advance_pdf_viewer: ^2.0.1
  animated_custom_dropdown: ^3.1.1
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  custom_refresh_indicator: ^4.0.1
  dio: ^5.6.0
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
  get: 4.6.6
  get_storage: any
  google_fonts: ^6.2.1
  http: ^1.2.2
  http_parser: any
  iconsax: ^0.0.8
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  intl: ^0.18.1
  persistent_bottom_nav_bar: ^5.0.2
  pull_to_refresh: ^2.0.0
  readmore: ^3.0.0
  shimmer_animation: ^2.1.0+1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
