name: flutter_talentaku
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.6
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  readmore: ^3.0.0
  persistent_bottom_nav_bar: ^5.0.2
  get_storage: any
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # uses-material-design: true
  assets:
    - assets/images/
